### ISSUE TITLE
hyperspace loop,can use it

### ISSUE THREAD

**Issue by thebear135** [HyperspaceApp/Hyperspace#1]
# BUG REPORT

 after app restart, he load and show screen with that:
Hyperspace Daemon v0.1.1
Git Revision 22278496
Loading...
(0/6) Loading hsd...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.646342 seconds

show de wallet with no information and show the scrren again

never stop to do that

and i never see my balance [](url)

**Environment**
Hyperspace version: v0.1.1
windows 10 pro x64
[hsd-output.log](https://github.com/HyperspaceApp/Hyperspace/files/2237666/hsd-output.log)
[host.log](https://github.com/HyperspaceApp/Hyperspace/files/2237669/host.log)

**Comment by huetsch** [comment]
We've had another report of this, also on Windows 10. Do you still have the issue? Are you able to reproduce it consistently?

**Comment by thebear135** [comment]
I fit it, we have to empty block folder and consensu.db and also reboot the
pc because only restart the wallet sosent work.

**Comment by huetsch** [comment]
We've been looking into this problem. We believe it's a recent bug we inherited from Sia. We'll be working on a fix once we've narrowed it down.

**Comment by ScottBAIC** [comment]
I have the same problem, running windows 10. Thanks. Will continue mining, but my wallet access is not possible.

**Comment by huetsch** [comment]
Hi guys, the code has changed significantly between v0.1.1 and v0.2.3. Please try the new wallet and file a new issue if the problem persist.
