### ISSUE TITLE
unable to load hyperspace wallet

### ISSUE THREAD

**Issue by sparkie73** [HyperspaceApp/Hyperspace#11]
# BUG REPORT

**Stack Trace or error message**

**Expected Behavior**

**How to reproduce it (as minimally and precisely as possible)**

**Environment**
* Hyperspace version:
* OS:

**Comment by sparkie73** [comment]
Hyperspace Daemon v0.1.1
Git Revision 22278496
Loading...
(0/6) Loading hsd...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 5.5072791 seconds

**Comment by sparkie73** [comment]
Hyperspace Daemon v0.1.1
Git Revision 22278496
Loading...
listen tcp 127.0.0.1:5580: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

**Comment by huetsch** [comment]
Hi. It looks like you're trying to run the daemon twice on the same machine. You can do that, but you need to tell it not to use the same ports. 

Also, if you're on a unix machine, you can check what's already listening on port 5580 with: `lsof -i :5580`

**Comment by sparkie73** [comment]
Thanks I will check, I'm on windows 10, but it does look like I have two
running.



Mark Martin.

Mobile 07445 323025
email mark7martin@googlemail.com

**Comment by huetsch** [comment]
Perhaps we should add a notification in both the CLI and the UI versions if we detect something is already on that port.

**Comment by sparkie73** [comment]
That would help, It may be easier if when you close the program that it stops running. I can only stop using task manager

**Comment by sparkie73** [comment]
Hi I've successfully synced and went to load my seed onto Hyperspace from my Sia wallet to claim the Hyperspace tokens, I inputted my Sia password after typing in the seed, but it doesnt recognise password and gives this error. Unlock error when calling /wallet/unlock: provided encryption key is incorrect.
It was the correct password for my Sia wallet as I was also able to change my Sia password. Do you have any idea what I may be doing wrong? I double checked the seed phrase.

**Comment by huetsch** [comment]
1) The daemon should have exited when you closed the app the first time. Not sure why it persisted.

2) Passwords only encrypt the seed locally. When you init a new wallet, the seed is default encrypted by itself. That is, use your seed as the password. That will probably allow you to unlock the wallet.

**Comment by sparkie73** [comment]
That worked a treat with the password. Thanks. My space cash is there :-)

Is that a usual thing for the seed to be encrypted by itself? will that work with other wallets?
Many thanks for your help. Happy Sunday
