### ISSUE TITLE
Unable to fund transaction: cannot create new address beyond address gap limit

### ISSUE THREAD

**Issue by gura** [HyperspaceApp/Hyperspace#23]
I am trying to send 5 Hyperspace Cash to wallet.  It is not sending and getting this error.

> error when calling /wallet/spacecash: unable to fund transaction: cannot create new address beyond address gap limit

**Environment**
Hyperspace version: v0.2.0
Hsd version: 0.2.0
Window 8.1
* Hyperspace version: 0.2
* OS: Windows 8.1

**Comment by huetsch** [comment]
Thank you for this report. Please try version 0.2.2 - we've resolved a number of related issues between 0.2.0 and 0.2.2.

**Comment by huetsch** [comment]
We believe we've eliminated all the old address gap limit issues in v0.2.3. I'm closing this for now.
