### ISSUE TITLE
Cannot create a wallet from seed or recover seed.

### ISSUE THREAD

**Issue by kakstuff** [HyperspaceApp/Hyperspace#28]
my last recorded transaction date is 2018-10-02
  i can back the wallet up  and it gives the origiinal seed .

 If i try to recover seed i get the  error,

error when calling /wallet/sweep/seed: cannot sweep primary seed

 if i install v1.1 I get this error , or v0.2.0 on a new PC is get this error

![recover seed](https://user-images.githubusercontent.com/44460862/47484795-e49e0a00-d83c-11e8-9ecd-cee40e2eaa13.png)

![walletfromseed](https://user-images.githubusercontent.com/44460862/47484833-026b6f00-d83d-11e8-9de1-0f121a3db4ba.png)

however i can unlock the wallet on the original installation

**Comment by huetsch** [comment]
This error indicates that you are inputting an improperly formatted seed. Try checking for whitespace at the beginning or end of the seed.
