### ISSUE TITLE
Hsd unexpectedly exited. Error log: Hyperspace Daemon 

### ISSUE THREAD

**Issue by hamedghodrati** [HyperspaceApp/Hyperspace#45]
A critical error loading Hyperspace has occured: Hsd unexpectedly exited. Error log: Hyperspace Daemon v0.2.0
Git Revision 76f89464b
Loading...
(0/4) Loading hsd...
(1/4) Loading gateway...
(2/4) Loading consensus...
(3/4) Loading transaction pool...
goroutine 1 [running]:
runtime/debug.Stack(0x4466ee, 0x0, 0xc000a1c0c8)
	/usr/local/opt/go/libexec/src/runtime/debug/stack.go:24 +0xae
runtime/debug.PrintStack()
	/usr/local/opt/go/libexec/src/runtime/debug/stack.go:16 +0x29
github.com/HyperspaceApp/Hyperspace/build.Critical(0xc000a1c3c8, 0x2, 0x2)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/build/critical.go:16 +0x9a
github.com/HyperspaceApp/Hyperspace/persist.(*Logger).Critical(0xc00022e000, 0xc000a1c3c8, 0x2, 0x2)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/persist/log.go:37 +0xd3
github.com/HyperspaceApp/Hyperspace/modules/consensus.(*ConsensusSet).computeConsensusChange(0xc00016a780, 0xc000278380, 0x0, 0x0, 0x0, 0xc0004095e0, 0x1, 0x1, 0x0, 0x0, ...)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/modules/consensus/subscribe.go:51 +0x1112
github.com/HyperspaceApp/Hyperspace/modules/consensus.(*ConsensusSet).managedInitializeSubscribe.func2(0xc000278380, 0xcb43e0, 0xc000278380)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/modules/consensus/subscribe.go:229 +0x19a
github.com/HyperspaceApp/Hyperspace/vendor/github.com/coreos/bbolt.(*DB).View(0xc000230000, 0xc00020ef30, 0x0, 0x0)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/vendor/github.com/coreos/bbolt/db.go:708 +0x97
github.com/HyperspaceApp/Hyperspace/modules/consensus.(*ConsensusSet).managedInitializeSubscribe(0xc00016a780, 0xd87b40, 0xc000bcb4a0, 0x0, 0x0, 0x0, 0x0, 0xc00004b080, 0x0, 0x0, ...)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/modules/consensus/subscribe.go:221 +0x3e8
github.com/HyperspaceApp/Hyperspace/modules/consensus.(*ConsensusSet).ConsensusSetSubscribe(0xc00016a780, 0xd87b40, 0xc000bcb4a0, 0x0, 0x0, 0x0, 0x0, 0xc00004b080, 0x0, 0x0)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/modules/consensus/subscribe.go:278 +0xf8
github.com/HyperspaceApp/Hyperspace/modules/transactionpool.(*TransactionPool).initPersist(0xc000bcb4a0, 0xc000bcb4a0, 0x4f)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/modules/transactionpool/persist.go:180 +0x8af
github.com/HyperspaceApp/Hyperspace/modules/transactionpool.New(0xd96a20, 0xc00016a780, 0xd943e0, 0xc0000da840, 0xc000022be0, 0x4f, 0x0, 0x0, 0x0)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/modules/transactionpool/transactionpool.go:101 +0x142
main.(*Server).loadModules(0xc0000da6e0, 0xcb4a88, 0xc00004a360)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/cmd/hsd/server.go:513 +0x24cb
main.startDaemon(0x0, 0x0, 0xc0000560cb, 0xe, 0xc0000580db, 0x5, 0xc00005610c, 0x5, 0x0, 0xc00005813a, ...)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/cmd/hsd/daemon.go:264 +0x2b9
main.startDaemonCmd(0xc000119680, 0xc0000d4720, 0x0, 0x6)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/cmd/hsd/daemon.go:318 +0x1b4
github.com/spf13/cobra.(*Command).execute(0xc000119680, 0xc00008c010, 0x6, 0x7, 0xc000119680, 0xc00008c010)
	/Users/mark/.go/src/github.com/spf13/cobra/command.go:766 +0x2d3
github.com/spf13/cobra.(*Command).ExecuteC(0xc000119680, 0xc7b076, 0xf, 0xc00015a960)
	/Users/mark/.go/src/github.com/spf13/cobra/command.go:852 +0x304
github.com/spf13/cobra.(*Command).Execute(0xc000119680, 0x1358ff8, 0xc68535)
	/Users/mark/.go/src/github.com/spf13/cobra/command.go:800 +0x32
main.main()
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/cmd/hsd/main.go:196 +0x7ee
Critical error: getBlockMap failed in computeConsensusChange: requested item does not exist
Please submit a bug report here: https://github.com/HyperspaceApp/Hyperspace/issues
requested item does not exist

plz help me

**Comment by huetsch** [comment]
Hi, thanks for your bug report. 

v0.2.0 is pretty old. Please try with the v0.2.3 release and see if you get the same issue. We've fixed many bugs between now and then. I'll close this for now, but please re-open if you see the issue on v0.2.3.
